### ISSUE TITLE
No manual booking if product type is Accommodations

### ISSUE THREAD

**Issue by ajgw** [woothemes/woocommerce-accommodation-bookings#15] opened 2016-01-29 09:02 UTC
I have only one product on client site: a room for rent, set up as Accommodation Booking. If I like to place a booking in backend as manual, I have to select the booking product. But because I have one product but only Accommodation, there is anything to select. Is doesn't show me the Accommodation as bookable product.

**Comment by solaceten** [comment] 2016-01-29 23:23
I was able to reproduce this issue also.

When the product is an "Accommodation" product, in Admin > Bookings > Create Booking the products do not show in the dropdown.

**Comment by TomasHurtz** [comment] 2016-02-03 13:39
I also have the very same problem.  Any idea when a release to the updated code will be made?  I see v 1.02 is in the works.

I foolishly installed this without testing and my client is going nuts because there is no manual booking.

**Comment by solaceten** [comment] 2016-02-09 12:49
Any further development on this please?

**Comment by gedex** [comment] 2016-02-09 14:57
> Any further development on this please?

Yes we're trying to release this under `1.0.2`, next release.

**Comment by gedex** [comment] 2016-02-12 10:04
Fixed in #24.

**Closed by gedex** 2016-02-12 10:04 UTC
Labels: [Pri] Normal, [Type] Bug
