### ISSUE TITLE
Compatibility issues with WooCommerce Stripe Gateway

### ISSUE THREAD

**Issue by larsmagnusherland** [woothemes/woocommerce-accommodation-bookings#48] opened 2016-04-13 18:26 UTC
This plugin does not work good with WooCommerce Booking and WooCommerce Stripe Gateway.
When you enable WooCommerce Stripe Gateway and have the two others enabled.
Using CreditCard on checkout results in a 500 error and never getting passed the checkout page.
Information goes to stripe and WooCommerce, but the order isn't fully processed.

Error from the logs state:
2016/04/13 13:49:09 [error] 14606#0: *3365 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/XXXX.com/wp-content/plugins/woocommerce-multilingual/compatibility/class-wcml-bookings.php on line 868
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/XXXX.com/wp-content/plugins/woocommerce-multilingual/compatibility/class-wcml-bookings.php on line 868" while reading response header from upstream, client: 109.189.206.149, server: www.XXXXX.com, request: "POST /wp-admin/post.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-XXXXX.sock:", host: "www.XXXXX.com", referrer: "https://www.XXXXX.com/wp-admin/post.php?post=381&action=edit&lang=fr

Disabling the woocommerce-accommodation-bookings plugin and making the product a normal Accommodation out of the product makes the checkout page work without issues.

**Comment by gedex** [comment] 2016-05-04 11:14
@larsmagnusherland the notices pasted above comes from `woocommerce-multilingual` plugin. We added POT file in #52 that hopefully fix issues with other translation plugins. Could you try disable woocommerce-multilingual or making sure only WC, Stripe, Bookings, and Accommodation Bookings are the ones active?

**Comment by gedex** [comment] 2016-05-04 12:47
Unable to reproduce this with latest WC, Bookings, and Accommodation Bookings. Here's my screencast:

![test-issues-48](https://cloud.githubusercontent.com/assets/78313/15014564/f13dca90-1230-11e6-9581-c53e96d9fe73.gif)

Closing this.

**Closed by gedex** 2016-05-04 12:47 UTC
Labels: [Pri] High, [Type] Bug
