### ISSUE TITLE
Product data options show duplicates w/ WooCommerce Subscriptions enabled

### ISSUE THREAD

**Issue by johndcoy** [woothemes/woocommerce-accommodation-bookings#74] opened 2016-09-13 15:47 UTC
#### Steps to reproduce the issue

1. Enable WooCommerce Accommodation and WooCommerce Subscriptions
2. Create an Accommodation Booking Product 
3. Product data options then show duplicate _Availability_ options and both _Costs_ and _Rates_, rather than just _Rates_ for Accommodations.
<img width="954" alt="screen shot 2016-09-13 at 7 44 24 am" src="https://cloud.githubusercontent.com/assets/2876178/18480710/4a1202aa-799f-11e6-9834-52e0f527e2a7.png">

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment] 2016-09-13 15:52
@johndcoy - any other detail to reproduce this? I just tested it and I am not seeing duplicate options.

**Comment by johndcoy** [comment] 2016-09-13 15:59
@roykho - Here is a list of a my current active plugins:

WooCommerce Version 2.6.4
WooCommerce Accommodation Booking Version 1.0.6
WooCommerce Bookings Version 1.9.12
WooCommerce Subscriptions Version 2.0.19

You can then create a new Accommodations product to replicate the issue.

Hope this helps!

**Comment by kristinaplauche** [comment] 2016-09-13 16:02
@jessepearson @ValeDeOro and I all replicated this issue. 
Accommodations 1.0.6
Bookings 1.9.12
Subscription 2.0.19
Opened up a previously created a accommodation product, or try to create a new accommodations product.  All the bookings tabs show up along with the Accommodations tab while Subscriptions is active.  Deactivate subscriptions and then only the Accommodations tabs appear.
![screen shot 2016-09-13 at 12 00 25 pm](https://cloud.githubusercontent.com/assets/16582518/18481351/e43871fc-79a9-11e6-99ec-15c4a9e623db.png)

**Comment by roykho** [comment] 2016-09-13 16:06
Ok I believe this issue was introduced in Subscriptions 2.0.18 or 2.0.19 because in my test 2.0.17 didn't have this issue.

**Comment by roykho** [comment] 2016-09-13 16:07
In fact, you don't need to create an accommodation product to see this. Just click "add product" and it will show duplicates.

**Comment by roykho** [comment] 2016-09-13 16:14
The issue came from this commit https://github.com/Prospress/woocommerce-subscriptions/commit/32e74d7045618c85811945792257cbc76586c85c

**Comment by roykho** [comment] 2016-09-13 21:21
Closing this as it is a subscriptions issue and already fixed in this commit here https://github.com/Prospress/woocommerce-subscriptions/pull/1637/commits/6bdfe73666b4a4604c00ffa37d5e7f167dabcd01

**Closed by roykho** 2016-09-13 21:21 UTC
Labels: [Status] Needs Author Reply
