### ISSUE TITLE
Date picker doesn't update booking dates

### ISSUE THREAD

**Issue by ValeDeOro** [woothemes/woocommerce-accommodation-bookings#68] opened 2016-07-29 14:50 UTC
#### What I expected

When manually changing the check-in and check-out dates, the price should update accordingly on the product page: 

![](https://cloudup.com/ckbavwY1QDV+)
https://cloudup.com/ckbavwY1QDV

#### What happened instead

First the customer chooses the date through the calendar that displays when clicking on "choose". Then they manually adjust the check-out date. The price doesn't change. 

![](http://cld.wthms.co/15RGL/4P6zzJMS+)
http://cld.wthms.co/15RGL/4P6zzJMS

#### Steps to reproduce the issue

WooCommerce 2.6.4
WooCommerce Bookings 1.9.10
WooCommerce Accommodation Bookings 1.0.5

Create a new Accommodation product with the following parameters: 

General: 
Min number of nights 1, max number of nights 7. 
*Calendar display mode: Display calendar on click*

![](https://cloudup.com/cARvzXsUlwn+)
https://cloudup.com/cARvzXsUlwn

Costs: 
Standard room rate: 100
![](https://cloudup.com/cD3_Klox-mm+)
https://cloudup.com/cD3_Klox-mm

Visit the product on the front-end. Choose a start-date and an end-date and see the price update. 
Now manually change the end-date. 
It *looks* as if the rate is being calculated again, but the value does not change. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by robertstaddon** [comment] 2016-07-30 20:25
@ValeDeOro Excellent bug report! The bug you have found is actually in the main WooCommerce Bookings plugin, not in the WooCommerce Accommodation Bookings extension plugin.

To reproduce this bug directly in WooCommerce Bookings, you must take the following steps:

1. Install WooCommerce & WooCommerce Bookings 
2. Create a Bookable product: 
- Set Booking duration to "Customer defined blocks of 1 Days" 
- Enable Calendar Range Picker 
- Leave Calendar display mode to the default "Display calendar on click"

I have done the above at http://test.abundantdesigns.com/product/room/, where you can see the bug in action without the WooCommerce Accommodation Plugin being installed.

The reason that this bug appears so readily in WooCommerce Accommodation Bookings is because out of the box it sets the Booking duration to "Customer defined blocks of 1 Days" and enables the Calendar range picker. 

I would really encourage you to file this as a bug report ticket with WooCommerce for their WooCommerce Bookings plugin. When the underlying problem is solved there, WooCommerce Accommodation Bookings will automatically be fixed.

If you want to work around this in the meantime, change your "Calendar display mode" to always display the calendar instead of displaying it on click.

**Comment by roykho** [comment] 2016-07-30 20:50
@ValeDeOro - @robertstaddon is correct this issue is in core Bookings. Closing this issue and I have already created the issue for you in Bookings here https://github.com/woothemes/woocommerce-bookings/issues/759

**Closed by roykho** 2016-07-30 20:50 UTC

**Comment by roykho** [comment] 2016-07-30 21:14
This issue is fixed in Bookings core here https://github.com/woothemes/woocommerce-bookings/pull/760/commits/3343bc3c19c9eec7d62e41bb6e0272cef4d0c7d9
